### ISSUE TITLE
The api server is offline

### ISSUE THREAD

**Issue by budko1989** [AuroraDAO/idex-api-docs#11]
> https://api.idex.market/

`This page (https://api.idex.market/) is currently offline. However, because the site uses Cloudflare's Always Online™ technology you can continue to surf a snapshot of the site. We will keep checking in the background and, as soon as the site comes back, you will automatically be served the live version. Always Online™ is powered by Cloudflare | Hide this Alert`

**Comment by raypulver** [comment]
API is back up.
