### ISSUE TITLE
API not working

### ISSUE THREAD

**Issue by thibault12** [AuroraDAO/idex-api-docs#15]
Hi,

I am trying to retrieve the ask and bids data using the api but it is not working.

When I do it through returnTicker, the ask and bids fields are always N/A. When I do it through returnOrderBook, it returns an empty object when no JSON is specified and when I specify a JSON, it returns that the market can't be found.

Could someone look into this please!

**Comment by aydinozkan** [comment]
Same issue here!

**Comment by TokenaExchange** [comment]
works if use https://api-regional.idex.market 
but I cant manage to make any trades so far, any help will be appreciated https://github.com/AuroraDAO/idex-api-docs/issues/14

**Comment by aydinozkan** [comment]
lowestAsk and highestBid are N/A for https://api-regional.idex.market/returnTicker as well.

**Comment by fubar** [comment]
This is an old issue that has since been resolved. Feel free to post another comment if you still need assistance.
