### ISSUE TITLE
return24Volume always returns "Cannot read property '0' of null"

### ISSUE THREAD

**Issue by ZombiesWithCoffee** [AuroraDAO/idex-api-docs#2]
I'm attempting to call your 'return24Volume' REST service and always receive {"error":"Cannot read property '0' of null"}

POST: https://api.idex.market/return24Volume

I'm calling the rest of your APIs without an issue.

**Comment by algpet** [comment]
same here for return24Volume

**Comment by fubar** [comment]
This is an old issue that has since been resolved; closing.
