### ISSUE TITLE
Next nonce error

### ISSUE THREAD

**Issue by orangeAndSuns** [AuroraDAO/idex-api-docs#20]
When I  tried to use endpoint returnNextNonce, I got an error {"result":"error","errors":["[LAMBDA-RUNNER]\n    FAILED TO INITIALIZE LAMBDA! \n    \n    Our initialization function expects either one or two arguments, however, \n    you provided 3 parameters.","Cannot set property 'agent' of undefined"]}.
A few days ago all was working.
Use API https://api.idex.market

**Comment by RZeynalov** [comment]
same mistake i have

**Comment by freezepro** [comment]
same

**Comment by kyletan7** [comment]
Geting the same error

**Comment by Rogier076** [comment]
I have the same error.

**Comment by Rogier076** [comment]
Seems to work now

**Comment by RZeynalov** [comment]
working
