### ISSUE TITLE
Random nonce broke my account

### ISSUE THREAD

**Issue by khranovsky1337** [AuroraDAO/idex-api-docs#21]
Due to not working API returnNextNonce method, i decided to use a very big random nonce. Then i finally placed order with an API, but now i even can't trade or withdraw on the site, cuz i changed nonce manually. Now when im tryna withdraw funds or place an order, a "nonce too low" error appears in a little window on site. API withdrawal doesnt work too says either nonce too low or Invalid signature. Thus, my funds r blocked, i cant do anything with my money!!! So when will u fix next nonce method or is it possible to reset nonce for my address or at least withdraw my funds? Or how do the site get the nonce? I checked its network activity, there's nothing like nonce. Or how do nonce generates? I wrote to the support in telegram, but they dont understand what im talking about, they think i just have an issue with nonce and cant use API, but i cant use ANYTHING now :(

**Comment by khranovsky1337** [comment]
I already used big nonce. Now i cant do anything, even on site

**Comment by fubar** [comment]
Stale issue, closing.

**Comment by khranovsky1337** [comment]
Yes, i sorted this out, now i somehow hardly withdraw my funds to another account and trading happy. Also i contacted ur support in telegram, but they didnt help me

**Comment by GoldRat** [comment]
I have the same issue and even can't withdraw. How did you do it?

**Comment by khranovsky1337** [comment]
well, i couldnt withdraw too, but i was calling withdraw function with big nonces a lot of time and then finally withdrew and then made a new address and it's all good now!
