### ISSUE TITLE
Invalid order signature

### ISSUE THREAD

**Issue by GoldRat** [AuroraDAO/idex-api-docs#24]
I'm trying to open order through API.

This is my payload:
{"contractAddress":"0x2a0c0dbecc7e4d658f48e01e3fa353f44050c208",
"tokenBuy":"0x0000000000000000000000000000000000000000",
"amountBuy":"50000000000000000",
"tokenSell":"0xcdcfc0f66c522fd086a1b725ea3c0eeb9f9e8814",
"amountSell":"100000000000000000000",
"expires":10000,
"nonce":1,
"address":"0x351296f44a5bf3f05eaa7d78a560f50dd736b728",
"v":28,
"r":"0xf58101acdb189a21a18d4b504b124dbfd3cfe67126b2fdc132eb3b3dea86664a",
"s":"0x50100b3e391b4fed0e6dcf81e3c833b971506b48d5c837bb81bbb1c6240c4c61"}

Private key: 0xce8291ae3e3f6db1f7d763fa543c1aa7c76080f69880d695bf131f4ca7bde67a

But it returns the error:
{"error":"Invalid order signature. Please try again."}

What's wrong with order signature? What v, r, s parameters values should be in this case? Please, help!

**Comment by khranovsky1337** [comment]
Hm, I had the same issue, looks like it's server problem. Sometimes it disappears and u can use api normally

**Comment by GoldRat** [comment]
Is there any examples to test hashing and signing? Like input parameters -> raw hash -> salted hash - > v, r, s

**Comment by fubar** [comment]
The documentation includes a JS code sample for creating signatures, and I've added a code sample with more detailed instructions specific to the OP's case to the other issue opened by the OP at https://github.com/AuroraDAO/idex-api-docs/issues/26. Closing.

**Comment by GoldRat** [comment]
I've tested my algorithm by example you've given at [#26](https://github.com/AuroraDAO/idex-api-docs/issues/26#issuecomment-406753162). The result is perfect match to your r, s, v values. However the error "Invalid order signature" still appears (not always but sometimes).
