### ISSUE TITLE
websockets not working

### ISSUE THREAD

**Issue by wasimjee** [AuroraDAO/idex-api-docs#28]
trying to use the websockets, but its not working

**Comment by ivanvanderbyl** [comment]
I can confirm the same issue, we get back a response to subscribe:

```json
{"message":{"success":"Subscribed to ETH_AURA"}}
{"message":{"success":"Subscribed to ETH_REM"}}
```

But then silence. I've tried this using the example code from the readme as well.

**Comment by fubar** [comment]
We have recently rolled out some changes and fixes to the WebSocket API. Note that we are working on a new version of our API offering that will replace the current one and introduce a number of breaking changes. Refer to the documentation at https://github.com/AuroraDAO/idex-api-docs#websocket-api for more info.
