### ISSUE TITLE
returnOrderBook

### ISSUE THREAD

**Issue by rfenzo** [AuroraDAO/idex-api-docs#3]
This API call is returning an empty dictionary, is it just me?

**Comment by Temperament** [comment]
Yea, can confirm. Tried running this today and other API calls i.e returnTicker work but not this one.

**Comment by raypulver** [comment]
Orderbook tracking on the API is down right now due to performance problems we were having affecting the main site, we'll close this once they are reimplemented.

**Comment by LanDeQuHuXi** [comment]
Just a suggestion:
Implement a Throttling for now and move it to websocket.

**Comment by gdolenc** [comment]
Any news on this one? When will be the orderbook API functioning again?

**Comment by 3hson** [comment]
is orderbook coming back any soon?

**Comment by bernar-r** [comment]
Update ?

**Comment by jfowler00** [comment]
@raypulver any idea when this is going to be back up?  Would be much appreciated :)

**Comment by sthewissen** [comment]
+1 - Would be appreciated to get this back :)

**Comment by orangeAndSuns** [comment]
any updates?

**Comment by fubar** [comment]
This is an old issue that has since been resolved; closing.
