### ISSUE TITLE
returnTicker not working as expected

### ISSUE THREAD

**Issue by yasinuslu** [AuroraDAO/idex-api-docs#4]
Hello, `returnTicker` endpoint is returning `{lowestAsk: "N/A", highestBid: "N/A"}` for all currencies. 

In this image you can see that we get `N/A` for ELEC
![image](https://user-images.githubusercontent.com/1007479/37246731-2988fcb4-24c0-11e8-8d7c-0a61a6482297.png)

And it's like that for all currencies:
![image](https://user-images.githubusercontent.com/1007479/37246764-b8002ff8-24c0-11e8-98d3-754240038107.png)

**Comment by DuYuNoDaWea** [comment]
I am having the exact same issue. N/A is the only value being returned for Ask and Bid. Only a few Volume values are populated with a value other than 0.

**Comment by jflyup** [comment]
the idex website is so shitty, laggy, broken, unstable and ugly, so I want use the API to do trade, in the end, the API is shit too. Look at their roadmap in the whitepaper, sigh.

**Comment by webcaetano** [comment]
Same here

**Comment by aydinozkan** [comment]
Is it going to be fixed soon?

**Comment by khranovsky1337** [comment]
I don't know, but u can use their api and get the full orderbook, where u can calculate bid and ask manually

**Comment by fubar** [comment]
This is an old issue that has since been resolved; closing.
