### ISSUE TITLE
Authentication Token?

### ISSUE THREAD

**Issue by pointtoken** [AuroraDAO/idex-api-docs#41]
When I tried to call **returnOpenOrders** aka https://api.idex.market/returnOpenOrders/ETH_SNT

I got 

```
{
    "message": "Missing Authentication Token"
}
```
However, nowhere in the docs is it explain how to get an authentication token or where to put it. Can someone help?

**Comment by bradennapier** [comment]
The url you have given is not a valid API call.  While generally a post to `returnOpenOrders` with a json object representing "market: "ETH_SNT" is best, we do support GET requests (undocumented) specifically for cases like this to show how a command should look when called:

https://api.idex.market/returnOpenOrders?market=ETH_SNT

**Comment by pointtoken** [comment]
Awesome -- works great and thx for the quick response.

**Comment by Apollo1993** [comment]
Goodjob
