### ISSUE TITLE
Is websocket fully working ?

### ISSUE THREAD

**Issue by ilampirai** [AuroraDAO/idex-api-docs#5]
Im trying to fetch some orderbook updates, But only received newTrade data.

**Comment by fubar** [comment]
We have recently rolled out some changes and fixes to the WebSocket API. Note that we are working on a new version of our API offering that will replace the current one and introduce a number of breaking changes. Refer to the documentation at https://github.com/AuroraDAO/idex-api-docs#websocket-api for more info.
