### ISSUE TITLE
OrderBook and OpenOrders errors 

### ISSUE THREAD

**Issue by ilampirai** [AuroraDAO/idex-api-docs#7]
{
	"market" : "ETH_ELEC"
}
returns 
{
    "error": "Market ETH_ELEC not found"
}

Another function openorders returns 
 "error": "Cannot read property 'toLowerCase' of undefined"

Is this web API working properly or is this in maintenance mode?

**Comment by fubar** [comment]
Stale issue that should be resolved. Let me know if you're still seeing any issues.
