### ISSUE TITLE
websocket API

### ISSUE THREAD

**Issue by Placid7** [AuroraDAO/idex-api-docs#9]
Are you going to update any of you websocket API documentation? There's nothing indicating what data is available. At this point the only thing returnable is the message stating that the subscribe is a success.

**Comment by Jsarnik** [comment]
bump.

**Comment by darkbing** [comment]
ReturnOrderBook does not work, websocket does not work either. It remains only to parse the site for order books. And with this approach, the site idex.market will definitely fall...
The API is needed to reduce the load on the site. What a stupidity to say that the API is, but in reality to disable half of the functions

**Comment by RonWalker22** [comment]
Please fix.

**Comment by ol-loginov** [comment]
same here - server closes websocket connection without any notification.

**Comment by sthewissen** [comment]
Server closes the connection soon after opening it and in that period I only receive `"type":"newTrade"` messages. I'm looking for order book data, so I'm hoping that can be enabled soon (preferably by `returnOrderbook`).

**Comment by wasimjee** [comment]
please provide an endpoint for connection.

**Comment by fubar** [comment]
We have recently rolled out some changes and fixes to the WebSocket API. Note that we are working on a new version of our API offering that will replace the current one and introduce a number of breaking changes. Refer to the documentation at https://github.com/AuroraDAO/idex-api-docs#websocket-api for more info.
